[template]
rename = [
  { from="tests/factorial_test.rs", to="tests/{{to_snake_case project-name}}_test.rs" },
]

[[placeholders]]
name = "vendor_name"
type = "string"
prompt = "Vendor name?"
default = "Acme"



